api:
  log_set_delete: false   # false = disable Set/Delete logs (for load tests)

gateway:
  shutdown_timeout: "5s"
  read_timeout: "0s"
  write_timeout: "0s"
  idle_timeout: "0s"

storage:
  cleanup_timeout: "5s"
  cleanup_cooldown: "5s"

graceful: true
