# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  general:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [skylr-shard, skylr-overseer]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
          cache: true

      - name: Verify dependencies ${{ matrix.dir }}
        run: |
          cd "${{ matrix.dir }}"
          go mod download
          go mod verify

      - name: Build ${{ matrix.dir }}
        run: |
          cd "${{ matrix.dir }}"
          go build -v ./...

      - name: Lint ${{ matrix.dir }}
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.6.2
          working-directory: ${{ matrix.dir }}
          args: --config=.golangci.yaml

      - name: Test ${{ matrix.dir }}
        run: |
          cd "${{ matrix.dir }}"
          make test
