# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  general:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [skylr-shard]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build ${{ matrix.dir }}
      run: | 
        cd "${{ matrix.dir }}"
        go build -v ./...

    - name: Test ${{ matrix.dir }}
      run: |
        cd "${{ matrix.dir }}"
        make test

    - name: Lint ${{ matrix.dir }}
      run: |
        cd "${{ matrix.dir }}"
        make lint
